'use client';

import { useState } from 'react';
import { Card } from '@/src/components/ui/Card';
import { Button } from '@/src/components/ui/Button';
import { Download, Filter } from 'lucide-react';

const reportTypes = [
  {
    title: 'Academic Performance',
    description: 'Class-wise and student-wise academic reports',
    icon: '📊',
    href: '/dashboard/admin/reports/academic',
  },
  {
    title: 'Financial Reports',
    description: 'Revenue, expenses, and fee collection reports',
    icon: '💰',
    href: '/dashboard/admin/reports/financial',
  },
  {
    title: 'Attendance Reports',
    description: 'Student and staff attendance tracking',
    icon: '✓',
    href: '/dashboard/admin/reports/attendance',
  },
  {
    title: 'Staff Performance',
    description: 'Teacher performance and evaluation reports',
    icon: '👨‍🏫',
    href: '/dashboard/admin/reports/staff',
  },
];

export default function ReportsPage() {
  const [dateRange, setDateRange] = useState({ start: '', end: '' });

  return (
    <div className="space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-3xl font-bold text-gray-900">Reports</h1>
        <p className="text-gray-600 mt-1">Generate and view various reports</p>
      </div>

      {/* Filters */}
      <Card>
        <div className="flex items-end gap-4 flex-wrap">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Start Date
            </label>
            <input
              type="date"
              value={dateRange.start}
              onChange={(e) => setDateRange({ ...dateRange, start: e.target.value })}
              className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
            />
          </div>
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              End Date
            </label>
            <input
              type="date"
              value={dateRange.end}
              onChange={(e) => setDateRange({ ...dateRange, end: e.target.value })}
              className="px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent outline-none"
            />
          </div>
          <Button variant="outline" className="flex items-center gap-2">
            <Filter size={18} />
            Apply Filters
          </Button>
        </div>
      </Card>

      {/* Report Types */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {reportTypes.map((report) => (
          <Card key={report.title} className="hover:shadow-lg transition-shadow cursor-pointer">
            <a href={report.href} className="block">
              <div className="flex items-start justify-between mb-4">
                <div className="text-4xl">{report.icon}</div>
                <Button variant="outline" size="sm" className="flex items-center gap-2">
                  <Download size={16} />
                  Export
                </Button>
              </div>
              <h3 className="text-lg font-bold text-gray-900">{report.title}</h3>
              <p className="text-sm text-gray-600 mt-1">{report.description}</p>
              <p className="text-xs text-blue-600 mt-3 font-medium">View Report →</p>
            </a>
          </Card>
        ))}
      </div>

      {/* Recent Reports */}
      <Card>
        <h2 className="text-lg font-bold text-gray-900 mb-4">Recently Generated</h2>
        <div className="space-y-3">
          {[1, 2, 3].map((i) => (
            <div key={i} className="flex items-center justify-between p-3 hover:bg-gray-50 rounded">
              <div>
                <p className="font-medium text-gray-900">Academic Report - {i === 1 ? 'Jan 2024' : `${i} month ago`}</p>
                <p className="text-xs text-gray-500">Generated by Admin</p>
              </div>
              <Button variant="outline" size="sm" className="flex items-center gap-2">
                <Download size={14} />
                Download
              </Button>
            </div>
          ))}
        </div>
      </Card>
    </div>
  );
}
